# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               "赫映 's blog"
tagline:             'silicon014'
description:         '普通的neet'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
gems:		     [jekyll-paginate]
# About/contact
author:
  name:              '赫映'
  url:               http://www.silicon014.com
  email:             Carbonc014@gmail.com

# Custom vars
version:             0.1.0
